export const Countries = [
    "Select Your Country",
    "United States of America",
    "China",
    "India",
    "Russia",
    "United Kingdom",
    "Germany",
    "France",
    "Canada",
    "Japan",
    "Brazil",
    "Australia",
    "South Korea",
    "Mexico",
    "Italy",
    "Spain",
    "Saudi Arabia",
    "Egypt",
    "South Africa",
    "Nigeria",
    "Argentina",
    "Turkey",
    "Iran",
    "Indonesia",
    "Pakistan",
    "Bangladesh",
    "Vietnam",
    "Thailand",
    "Philippines",
    "Singapore",
    "Malaysia",
    "New Zealand",
];


export const projects =[
    {
        image:'/mikasa.png',
        title:"Noteworthy technology acquisitions 2021",
        shortdescription:"Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.",
    },
    {
        image:'/mikasa.png',
        title:"Noteworthy technology acquisitions 2021",
        shortdescription:"Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.",
    },
    {
        image:'/mikasa.png',
        title:"Noteworthy technology acquisitions 2021",
        shortdescription:"Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.",
    },
    {
        image:'/mikasa.png',
        title:"Noteworthy technology acquisitions 2021",
        shortdescription:"Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.",
    },
    {
        image:'/mikasa.png',
        title:"Noteworthy technology acquisitions 2021",
        shortdescription:"Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.",
    },
    {
        image:'/mikasa.png',
        title:"Noteworthy technology acquisitions 2021",
        shortdescription:"Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.",
    },
    {
        image:'/mikasa.png',
        title:"Noteworthy technology acquisitions 2021",
        shortdescription:"Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.",
    },
    {
        image:'/mikasa.png',
        title:"Noteworthy technology acquisitions 2021",
        shortdescription:"Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.",
    },
    {
        image:'/mikasa.png',
        title:"Noteworthy technology acquisitions 2021",
        shortdescription:"Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.",
    },
]