export const Countries = [
    "Select Your Country",
    "United States of America",
    "China",
    "India",
    "Russia",
    "United Kingdom",
    "Germany",
    "France",
    "Canada",
    "Japan",
    "Brazil",
    "Australia",
    "South Korea",
    "Mexico",
    "Italy",
    "Spain",
    "Saudi Arabia",
    "Egypt",
    "South Africa",
    "Nigeria",
    "Argentina",
    "Turkey",
    "Iran",
    "Indonesia",
    "Pakistan",
    "Bangladesh",
    "Vietnam",
    "Thailand",
    "Philippines",
    "Singapore",
    "Malaysia",
    "New Zealand",
];


export const Demoprojects =[
    {   id:1,
        image:'/mikasa.png',
        title:"Noteworthy technology acquisitions 2021",
        shortdescription:"Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.",
    },
    {    id:2,
        image:'/mikasa.png',
        title:"Noteworthy technology acquisitions 2021",
        shortdescription:"Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.",
    },
    {    id:3,
        image:'/mikasa.png',
        title:"Noteworthy technology acquisitions 2021",
        shortdescription:"Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.",
    },
    {   
        id:4,
        image:'/mikasa.png',
        title:"Noteworthy technology acquisitions 2021",
        shortdescription:"Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.",
    },
    {   id:5,
        image:'/mikasa.png',
        title:"Noteworthy technology acquisitions 2021",
        shortdescription:"Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.",
    },
    {   
        id:6,
        image:'/mikasa.png',
        title:"Noteworthy technology acquisitions 2021",
        shortdescription:"Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.",
    },
    {   
        id:7,
        image:'/mikasa.png',
        title:"Noteworthy technology acquisitions 2021",
        shortdescription:"Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.",
    },
    {   
        id:8,
        image:'/mikasa.png',
        title:"Noteworthy technology acquisitions 2021",
        shortdescription:"Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.",
    },
    {   
        id:9,
        image:'/mikasa.png',
        title:"Noteworthy technology acquisitions 2021",
        shortdescription:"Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.",
    },
]



export const Institution = [
    "Select",
    "Maharshi Dayanand University",
    "University Institute Of Engineering and Technology",
    "Indian Institute of Technology, Delhi",
    "Indian Institute of Technology, Bombay",
    "Indian Institute of Technology, Madras",
    "Indian Institute of Technology, Kharagpur",
    "Priyadarshini BHAGWATI College of Engineering",
    "Y. B. Patil Polytechnic",
    "Sinhgad Institute of Business Management",
    "Shree Datta Polytechnic College",
    "Guru Nanak Institute of Management Studies",
    "Late Vasantdada Polytechnic",
    "Manoharbhai Patel Institute of Pharmacy, Gondia",
    "JSPM Narhe Technical Campus",
    "Trinity Polytechnic, Pune",
    "Yashwantrao Chavan School of Rural Development",
    "Padmashree Dr. D. Y. Patil B-SCHOOL",
    "Dr. A. D. Shinde College of Engineering",
    "A.I.'S MOHAMMED HAJI SABOO SIDDIK POLYTECHNIC",
    "Shri Sai College of Engineering",
    "Shri Mukundrao Pannase Polytechnic",
    "Mauli College of Pharmacy(B.PHARM)",
    "Institute of Management Studies",
    "Vidya Prasarak Mandal's Polytechnic, Thane",
    "St. Xavier's Technical Institute",
    "Government Polytechnic, Kendrapara",
    "The University of Burdwan: MBA(HR) PROGRAMME",
    "Omdayal Group of Institutions",
    "Nalanda Institute of Technology",
    "Ideal School of Engineering",
    "BHAVANI POLYTECHNIC COLLEGE",
    "RAJAJI INSTITUTE OF TECHNOLOGY",
    "KUMARAGURU COLLEGE OF TECHNOLOGY",
    "KARPAGAM INSTITUTE OF TECHNOLOGY",
    "M.A.R. COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "DR. VARSHA PATIL INSTITUTE OF TECHNOLOGY",
    "370 PALLAVAN POLYTECHNIC COLLEGE",
    "SSR INSTITUTE OF MANAGEMENT & RESEARCH",
    "SVKM'S DR. BHANUBEN NANAVATI COLLEGE OF PHARMACY",
    "JA G. H. RAISONI POLYTECHNIC",
    "GOVERNMENT POLYTECHNIC, BRAMHAPURI",
    "SWAMI VIVEKANAND SANTHA INSTITUTE OF PHARMACY",
    "NETAJI SUBHASH ENGINEERING COLLEGE",
    "LAL BAHADUR SHASTRI POLYTACHNIC INSTITUTE, TONDAR",
    "SINHGAD BUSINESS SCHOOL",
    "SMT. RADHIKATAI PANDAV COLLEGE OF ENGINEERING",
    "SHARADCHANDRA PAWAR COLLEGE OF ENGINEERING",
    "NAGPUR INSTITUTE OF TECHNOLOGY",
    "BAJAJ CHANDRAPUR POLYTECHNIC CHANDRAPUR",
    "SANJIVANI K.B.P.POLYTECHNIC, KOPARGAON",
    "HI-TECH POLYTECHNIC",
    "D.B.GROUP OF INSTITUTIONS, SCHOOL OF TECHNOLOGY",
    "HI-TECH INSTITUTE OF TECHNOLOGY",
    "DHABALESWAR INSTITUTE OF POLYTECHNIC",
    "COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "JAIN INSTITUTE OF MANAGEMENT & ENTREPRENEURSHIP",
    "KEONJHAR SCHOOL OF ENGINEERING, KEONJHAR",
    "SRI SARADA COLLEGE OF PHARMACY",
    "BIRBHUM INSTITUTE OF ENGINEERING & TECHNOLOGY",
    
    ]